---

name: bosh_simple_with_link

releases:
  - name: bosh-simple-spacebears
    version: latest

stemcells:
  - alias: bosh-warden-boshlite-ubuntu-trusty-go_agent
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: spacebears_db_node
    instances: 1
    azs: [z1]
    jobs:
      - name: spacebears
        release: bosh-simple-spacebears
    properties:
      spacebears:
        password: symphony27_Trailers
    vm_type: default
    cloud_properties:
      tags:
        - allow-ssh
    stemcell: bosh-warden-boshlite-ubuntu-trusty-go_agent
    persistent_disk_type: default
    networks:
      - name: default
